version: '3'

services: 
    web:
        image: nginx
        ports:
            - "8000:80"
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./code:/code
            - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: ./conf/php
        volumes:
            - ./code:/code
            - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./conf/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./logs/app:/code/logs
        networks:
            - code-network
    mariadb:
        image: mariadb:10.4
        command: "mysqld --init-file /data/application/init.sql"
        volumes:
            - ./conf/mariadb/scripts/init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
        restart: always
        ports:
            - 3333:3306
        networks:
            - code-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8081:80
        environment:
            - PMA_HOST=mariadb
        restart: always
        depends_on:
            - mariadb
        networks:
            - code-network
networks: 
    code-network:
        driver: bridge